# Generated by Django 6.0.2 on 2026-07-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paymentwebhook_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherPaymentMethods",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("payment_method", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "other_payment_methods",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_transac_ceca2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_status_426d4f_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_user_id_1b771c_idx",
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="payload",
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentwebhook",
            name="signature",
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                blank=True, default="squad", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="order_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="status",
            field=models.CharField(default="received", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="webhook_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="NGN", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentwebhook",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_transaction_ref",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
    ]
