# Generated by Django 6.0.2 on 2026-07-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_otherpaymentmethods_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="squad_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
