# Generated by Django 6.0.2 on 2026-07-04 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0002_adminuser_password_hash_alter_appsettings_updated_by"),
        ("support", "0002_conversationcontext"),
        ("vendors", "0004_vendorapplications_vendorsessions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("category", models.TextField()),
                ("order_index", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "faqs",
            },
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="contactbranch",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="is_internal",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="message",
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="message_content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="sender_role",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="order_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                db_column="assigned_to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to="admin_api.adminuser",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                db_column="resolved_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_tickets",
                to="admin_api.adminuser",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="vendors.vendor",
            ),
        ),
    ]
