# Generated by Django 6.0.2 on 2026-07-04 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_phase2_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorApplications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_id", models.UUIDField(blank=True, null=True)),
                ("application_type", models.TextField()),
                ("status", models.TextField()),
                ("submitted_data", models.JSONField()),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "vendor_applications",
            },
        ),
        migrations.CreateModel(
            name="VendorSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("session_token", models.TextField(unique=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, null=True)),
                ("ip_address", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "vendor_sessions",
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="billing_period",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="vendorbankaccount",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="vendorbankaccount",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.TextField(default="monthly"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="limits",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="available_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pending_payouts",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_paid_out",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="vendorbankaccount",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorbankaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorbankaccount",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorbankaccount",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorbankaccount",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="vendorsizecharttemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_column="approved_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
