# Generated by Django 6.0.2 on 2026-07-06 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_deliveryinfo_dynamicsizechartfields_featureposters_and_more",
        ),
        ("vendors", "0004_vendorapplications_vendorsessions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("cart", "Cart"),
                            ("checkout", "Checkout"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="products.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "product_analytics_events",
                "indexes": [
                    models.Index(
                        fields=["vendor", "event_type", "created_at"],
                        name="product_ana_vendor__9781fc_idx",
                    ),
                    models.Index(
                        fields=["product", "event_type", "created_at"],
                        name="product_ana_product_e9fa40_idx",
                    ),
                ],
            },
        ),
    ]
