# Generated by Django 6.0.1 on 2026-07-07 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_phase2_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.TextField()),
                ("key", models.TextField()),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "platform_settings",
            },
        ),
        migrations.RemoveField(
            model_name="promotionalbanner",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="promotionalbanner",
            name="link_url",
        ),
        migrations.RemoveField(
            model_name="promotionalbanner",
            name="page_location",
        ),
        migrations.RemoveField(
            model_name="promotionalbanner",
            name="position",
        ),
        migrations.RemoveField(
            model_name="promotionalbanner",
            name="text_color",
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="background_image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="banner_height",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="coupon_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="coupon_code_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="description_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="discount_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="discount_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="discount_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="overlay_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_background_image",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_coupon_code",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_description",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_discount",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_subtitle",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="show_title",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="subtitle_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="text_alignment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="title_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="background_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="banner_size",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="border_radius",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="button_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="button_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="button_text_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="created_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="custom_styles",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="is_template",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="padding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="show_button",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="template_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
