# Generated by Django 6.0.2 on 2026-06-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_squad_gateway_ref_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

