# Generated by Django 6.0.1 on 2026-07-07 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_auto_20260616_0556"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_id", models.UUIDField()),
                ("previous_status", models.TextField(blank=True, null=True)),
                ("new_status", models.TextField()),
                ("changed_by", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_status_history",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_discount_applied",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="loyalty_voucher_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
