# Generated by Django 6.0.1 on 2026-06-13 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_video_url_alter_product_sizes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaUploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("result_url", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "media_upload_jobs",
            },
        ),
    ]
