# Generated by Django 6.0.2 on 2026-07-04 09:14

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_mediauploadjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(unique=True)),
                ("return_window_days", models.IntegerField(blank=True, null=True)),
                ("cod_eligible", models.BooleanField(blank=True, null=True)),
                ("free_delivery", models.BooleanField(blank=True, null=True)),
                (
                    "shipping_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("eta_min_days", models.IntegerField(blank=True, null=True)),
                ("eta_max_days", models.IntegerField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "delivery_info",
            },
        ),
        migrations.CreateModel(
            name="DynamicSizeChartFields",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size_chart_id", models.UUIDField()),
                ("field_name", models.TextField()),
                ("field_type", models.TextField()),
                ("field_unit", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(blank=True, null=True)),
                ("field_options", models.JSONField(blank=True, null=True)),
                ("placeholder_text", models.TextField(blank=True, null=True)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dynamic_size_chart_fields",
            },
        ),
        migrations.CreateModel(
            name="FeaturePosters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("title", models.TextField()),
                ("subtitle", models.TextField()),
                ("media_url", models.TextField()),
                ("aspect_ratio", models.TextField(blank=True, null=True)),
                ("cta_label", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "feature_posters",
            },
        ),
        migrations.CreateModel(
            name="ProductApprovalQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("vendor_id", models.UUIDField()),
                ("action_type", models.TextField()),
                ("status", models.TextField()),
                ("submitted_data", models.JSONField()),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_approval_queue",
            },
        ),
        migrations.CreateModel(
            name="ProductHighlights",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("label", models.TextField()),
                ("icon_url", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_highlights",
            },
        ),
        migrations.CreateModel(
            name="ProductOffers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("type", models.TextField()),
                ("code", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("icon_url", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_offers",
            },
        ),
        migrations.CreateModel(
            name="ProductRecommendations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(unique=True)),
                (
                    "similar_products",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                (
                    "from_seller_products",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                (
                    "you_might_also_like",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                ("algorithm_version", models.TextField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_recommendations",
            },
        ),
        migrations.CreateModel(
            name="ProductReviewsSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(unique=True)),
                ("with_media", models.IntegerField(blank=True, null=True)),
                (
                    "histogram",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                ("total_reviews", models.IntegerField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_reviews_summary",
            },
        ),
        migrations.CreateModel(
            name="ProductSizeChartAssignments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("vendor_template_id", models.UUIDField(blank=True, null=True)),
                ("custom_data", models.JSONField(blank=True, null=True)),
                ("assignment_type", models.TextField()),
                ("assigned_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_size_chart_assignments",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("group_name", models.TextField()),
                ("spec_name", models.TextField()),
                ("spec_value", models.TextField()),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_specifications",
            },
        ),
        migrations.CreateModel(
            name="ProductViews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_views",
            },
        ),
        migrations.CreateModel(
            name="SizeChartAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("vendor_template_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("action_type", models.TextField()),
                ("selected_size", models.TextField(blank=True, null=True)),
                ("session_id", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "size_chart_analytics",
            },
        ),
        migrations.CreateModel(
            name="SizeChartEntries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("size_name", models.TextField()),
                ("measurements", models.JSONField()),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "size_chart_entries",
            },
        ),
        migrations.CreateModel(
            name="SizeChartMigrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size_chart_id", models.UUIDField()),
                ("old_measurement_types", models.JSONField(blank=True, null=True)),
                ("migration_status", models.TextField(blank=True, null=True)),
                ("migration_notes", models.TextField(blank=True, null=True)),
                ("migrated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "size_chart_migration_log",
            },
        ),
        migrations.CreateModel(
            name="SizeChartTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("category_id", models.UUIDField(blank=True, null=True)),
                ("subcategory", models.TextField(blank=True, null=True)),
                ("measurement_types", models.JSONField()),
                ("measurement_instructions", models.TextField(blank=True, null=True)),
                ("size_recommendations", models.JSONField(blank=True, null=True)),
                ("chart_type", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "size_chart_templates",
            },
        ),
        migrations.CreateModel(
            name="WarrantyInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(unique=True)),
                ("type", models.TextField()),
                ("duration", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("terms_url", models.TextField(blank=True, null=True)),
                ("coverage_details", models.TextField(blank=True, null=True)),
                ("exclusions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "warranty_info",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="base_currency",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="box_contents",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cod_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color_images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="converted_prices",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_size_chart_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="orders_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="safety_notes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart_override",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart_template_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_guide_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sizing_required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="usage_instructions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="vendor_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
