# Generated by Django 6.0.1 on 2026-07-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_deliveryinfo_dynamicsizechartfields_featureposters_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productquestion",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
